# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class 20231224GoCliTest < Formula
  desc ""
  homepage ""
  version "0.0.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ny-a/2023-12-24-go-cli-test/releases/download/v0.0.4/2023-12-24-go-cli-test_Darwin_arm64.tar.gz"
      sha256 "9b675b01265dda7831f0b6f93b86255bc04d27c52ddc0744b3a0f67f98dfe1f7"

      def install
        bin.install "2023-12-24-go-cli-test"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ny-a/2023-12-24-go-cli-test/releases/download/v0.0.4/2023-12-24-go-cli-test_Darwin_x86_64.tar.gz"
      sha256 "c7e7aa2833c5260537626cb4366e9429691efe978b2ff644537987ee8abb3438"

      def install
        bin.install "2023-12-24-go-cli-test"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ny-a/2023-12-24-go-cli-test/releases/download/v0.0.4/2023-12-24-go-cli-test_Linux_x86_64.tar.gz"
      sha256 "ee780948385b6d1be7c2a64caa4a7dee426d75b5e84451ceb270cbb3a2aa084d"

      def install
        bin.install "2023-12-24-go-cli-test"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ny-a/2023-12-24-go-cli-test/releases/download/v0.0.4/2023-12-24-go-cli-test_Linux_arm64.tar.gz"
      sha256 "a073af2fb836c9d36843e40a03a89c73aeeefd139950f9e7e2c8e3e67aac34dc"

      def install
        bin.install "2023-12-24-go-cli-test"
      end
    end
  end
end
